export const mockData = [
  { title: "title_1", id: "title_1" },
  { title: "title_2", id: "title_2" },
  { title: "title_3", id: "title_3" },
  { title: "title_4", id: "title_4" },
  { title: "title_5",  id: "title_5" },
  { title: "title_6", id: "title_6" },
  { title: "title_7", id: "title_7" },
  { title: "title_8", id: "title_8" },
  { title: "title_9", id: "title_9" },
  { title: "title_10", id: "title_10" },
  { title: "title_11", id: "title_11" },
  { title: "title_12", id: "title_12" },
  { title: "title_13", id: "title_13" },
  { title: "title_14",  id: "title_14" },
  { title: "title_15", id: "title_15" },
  { title: "title_16", id: "title_16" },
  { title: "title_17", id: "title_17" },
  { title: "title_18", id: "title_18" },
  { title: "title_19",  id: "title_19" },
  { title: "title_20", id: "title_20" },
];
